name: hikedex
description: A new way to hike.
publish_to: "none"

version: 8.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_location_marker: ^6.0.0
  flutter_map_marker_cluster: ^1.1.1
  flutter_svg: ^2.0.7
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  latlong2: ^0.8.1
  provider: ^6.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/hd_icons/
